var JSON_DATA = {
   "status":"ok",
   "version":"3.403",
   "request":{
      "route":"/get-status"
   },
   "response":{
      "preset":1,
      "time":"2018-09-04 18:10",
      "switches":[
         {
            "id":0,
            "type":"switch",
            "status":"off"
         },
         {
            "id":1,
            "type":"switch",
            "status":"on"
         },
         {
            "id":2,
            "type":"switch",
            "status":"off"
         },
         {
            "id":3,
            "type":"switch",
            "status":"off"
         },
         {
            "id":4,
            "type":"switch",
            "status":"off"
         },
         {
            "id":5,
            "type":"switch",
            "status":"off"
         },
         {
            "id":8,
            "type":"switch",
            "status":"on"
         },
         {
            "id":9,
            "type":"switch",
            "status":"off"
         }
      ],
      "uvmeters":[

      ],
      "windmeters":[
         {
            "id":4,
            "unit":0,
            "ws":0.0,
            "dir":"NNE 22",
            "gu":0.0,
            "wc":23.5,
            "te":23.5,
            "favorite":"no"
         }
      ],
      "rainmeters":[
         {
            "id":3,
            "mm":5.6,
            "3h":0.0,
            "favorite":"no"
         }
      ],
      "thermometers":[
         {
            "id":0,
            "te":23.5,
            "hu":69,
            "favorite":"no"
         },
         {
            "id":1,
            "te":23.1,
            "hu":66,
            "favorite":"no"
         },
         {
            "id":2,
            "te":24.9,
            "hu":62,
            "favorite":"no"
         }
      ],
      "weatherdisplays":[

      ],
      "energymeters":[

      ],
      "energylinks":[

      ],
      "heatlinks":[

      ],
      "kakusensors":[
         {
            "id":0,
            "status":"no",
            "timestamp":"12:54"
         },
         {
            "id":1,
            "status":null,
            "timestamp":"00:00"
         }
      ]
   }
}